### ISSUE TITLE
Run array jobs (and nesting bugs)

### ISSUE THREAD

**Issue by DEHewitt** [DEHewitt/portunid_particle_tracking#12]
Once #11 is closed we should move to attempting to run these as array jobs on Katana

**Comment by DEHewitt** [comment]
Initial attempt unsuccessful changes and error message (from Katana) published in `Array-jobs` branch

**Comment by jaseeverett** [comment]
Sorry but I don't have any experience with MPI. Why are you using it? Is it to do with the nesting that it needs to run in parallel?
If you can't solve it, send Duncan et al. at ResTech an email with the Katana location of all the files and ask him. He should be able to get it running pretty quickly

**Comment by HaydenSchilling** [comment]
We seem to need MPI to run it (not sure why, it was the same before the nesting), without loading the MPI module, we got an error saying no MPI module could be located. I was assuming this was a step closer.

**Comment by DEHewitt** [comment]
Email sent to ResTech. Will provide an update on response.

**Comment by DEHewitt** [comment]
Array jobs appear to be working. On the road today but will thoroughly check on Monday and update repo/close issue.

**Comment by DEHewitt** [comment]
Array jobs working. Not close until recoded with release location x year array (similar to forward releases for the Tailor tracking).

**Comment by DEHewitt** [comment]
Still having trouble running array jobs. Getting one of the following errors:
1. Huge text file (attached): the coordinates that are causing dramas are all around the northern boundary of the ROMS model. I think it is related to OceanParcels/parcels#406
2. Katana generated email "Post job file processing error; job 473098[7].kman.restech.unsw.edu.au on host k023". I got this email only for jobs that didn't have the above mentioned text file. The walltime request = 100 hours and memory = 20gb.

For now I am going to push ahead and run each year as a separate submission.

[back_array.txt](https://github.com/DEHewitt/portunid_particle_tracking/files/4985124/back_array.txt)

**Comment by DEHewitt** [comment]
Have posted an issue (OceanParcels/parcels#889) to the main Parcels page regarding this.

**Comment by jaseeverett** [comment]
Thanks @DEHewitt. I've had that many times. My recollection is that it is only a warning (not an error) that the particle has gone out of bounds (as you suggest). Obviously that is only when running a single model (no nesting).

I think you are right. It will be related to where the models join. I have no idea how you do this (I must look at your code to learn - very cool) but is it because there is a gap in the join? Or is it supposed to be seamless?

Good luck!

**Comment by DEHewitt** [comment]
Cheers @jaseeverett - I think that you're right about it being a warning rather than an error. The output certainly seems to be fine (i.e. the particle trajectories don't look abnormal), so I expect that this is a built-in function of parcels to correct for this sort of thing. I think the issue is that we're releasing so many particles that the whole process becomes too computationally intensive and the job either times out or there isn't enough memory requested (hence the post job error). 

It was surprisingly straightforward to get the nesting to work (provided it _is working_). In the file `nest_BRAN_ROMS.py`: You define the fieldsets as normal (e.g. L48-67 and L70-93) then combine them by calling the `NestedField` function and defining the fieldset again (L104-108).

**Comment by jaseeverett** [comment]
Sorry @DEHewitt 

I'm just going back through your other comments now.

> Still having trouble running array jobs. Getting one of the following errors:
> 
> 1. Huge text file (attached): the coordinates that are causing dramas are all around the northern boundary of the ROMS model. I think it is related to [OceanParcels/parcels#406](https://github.com/OceanParcels/parcels/issues/406)

As above, this is the boundaries and is a warning. But shouldn't your particles continues through the northern ROMS boundary into the BlueLink model? They shouldn't get out of bounds until the northern boundary of your blue link run.

> 2. Katana generated email "Post job file processing error; job 473098[7].kman.restech.unsw.edu.au on host k023". I got this email only for jobs that didn't have the above mentioned text file. The walltime request = 100 hours and memory = 20gb.

I think "Post job file...."  Error means it has failed for some reason other than a code error. ie out of memory, time, no HD space to save the file. IT should be able to tell you if you email them. Back in the old days the error messages would tell you (ie over walltime) but not any more.

**Comment by HaydenSchilling** [comment]
I have tried a few things and posted an update on the Parcels issue (It's closed so we may need to reopen it if there is no response). Summary the development version on Github does not like our code, Katana does not like Python 3.8 so I have gone back to 3.6 which works fine with v2.2.0 (except the large amount of can't find the cell errors).

**Comment by HaydenSchilling** [comment]
Erik says to fix the correct cell not found warning on Katana it will likely require a full redevelopment of the nesting functions because it does not handle curvilinear grids very well. His solution was to find a work-around or try and develop it ourselves (I would love to contribute but this is likely beyond me).

I will attempt to proceed with a work-around while Dan forges ahead with BRAN only.
