### ISSUE TITLE
Bathymetry not in BRAN

### ISSUE THREAD

**Issue by HaydenSchilling** [DEHewitt/portunid_particle_tracking#14]
BRAN does not appear to have a bathymetry layer so we need to make a work-around if we wish to identify particles which settle in areas of set bathymetry.

I suggest we make a script which takes the particle positions (maybe final positions only) and matches it to a Bathymetry data file. I would use GEBCO unless we can find a more high-res Australia focused one. Maybe [[here](http://www.ausseabed.gov.au/)] (but looks like it might not cover the whole area)

**Comment by jaseeverett** [comment]
That is one way to do it, but BRAN will have bathymetry (it needs it to run). It might not be posted in a clear location online. Can you post the web address of the BRAN output here? I can have a look.

**Comment by HaydenSchilling** [comment]
Thanks, Here is the link to the BRAN files.
http://dapds00.nci.org.au/thredds/catalog/gb6/BRAN/BRAN_2016/catalog.html 

I did find a grid file in "misc/grid_spec.nc" which looked promising but the variables were not clear what they were.

**Comment by jaseeverett** [comment]
Hmm. Yeah I can't find it in that version. Have you spoken to Peter Oke? I assume this is the same version of BRAN that Collette uses as the boundary of her EastCoast ROMS runs?
Perhaps ask Collette?

**Comment by jaseeverett** [comment]
It may not be explicitly defined in the model output. 
You can build your own at worst case.
I think `zt` and `zb` are top(t) and bottom(b) of the depth bins. If you take 1 output file (for say temperature), you can work out which vertical cell (for each lat/lon cell) is the last one with a value. This will be the bottom cell of the model run. Then that will correspond to `zt` and `zb` which will tell you the bottom depth. It will of course be coarser than ROMS because of the resolution.

**Comment by HaydenSchilling** [comment]
We emailed Peter Oke once after Colette tried to e-introduce us but didn't get a response. We'll ask Colette about if she knows. Yes it is the same version of BRAN she used for her model. Thanks!

**Comment by jaseeverett** [comment]
I doubt he is even involved with BRAN anymore. He is running the Argo programme. But the CSIRO BRAN websites are so out of date, there are no updated names attached. I can give Mark Baird a call and ask him who is in charge of it now. Would be good for you to have a direct contact for any issues.

**Comment by HaydenSchilling** [comment]
Yeah, I noticed the BRAN websites were not current. It would be good if you could ask Mark Baird if there is a current contact. Thanks

**Comment by DEHewitt** [comment]
The bathymetry product used in ROMS (available here: http://www.ga.gov.au/ausgeonews/ausgeonews200909/bathymetry.jsp) covers the whole Australian EEZ with a resolution of 250m.

**Comment by HaydenSchilling** [comment]
Bathymetry within the BRAN model is this one I'm pretty sure
variable = 'depth_t'
http://dapds00.nci.org.au/thredds/dodsC/gb6/BRAN/BRAN_2016/misc/grid_spec.nc.html

**Comment by DEHewitt** [comment]
Bathymetry now included from "grid_spec.nc" file.
