### ISSUE TITLE
Update BRAN Model

### ISSUE THREAD

**Issue by HaydenSchilling** [DEHewitt/portunid_particle_tracking#21]
CSIRO has told us there are mulitple BRAN models.
We are currently using BRAN2016 (1994-2016). We should also do BRAN2015 (2009-2019).

The BRAN2015 will be the best to match catch data as it aligns with reporting changes in the fishery. We can also compare the overlapping years.

**Comment by DEHewitt** [comment]
I have downloaded BRAN2015 and running simulations today. 2019 is problematic as model only runs until March (end of GMC spawning).
