### ISSUE TITLE
Unresolved conflict

### ISSUE THREAD

**Issue by jaseeverett** [DEHewitt/portunid_particle_tracking#24]
@DEHewitt There is an unresolved conflict in the .pbs submission script you are using for the backwards simulations. This file was last edited 7 days ago. I assume this isn't the PBS submission script you are using? If so, this is likely the problem with the backwards simulations (but I can't imagine how it is even running....)

https://github.com/DEHewitt/portunid_particle_tracking/blob/7d33032f69d8c5f44580c3ac6f6d7bdddf66142f/Simulations/gmc_back_bran2015.pbs#L1-L38

**Comment by DEHewitt** [comment]
I think this was caused by a mistake I made when pushing changes to GitHub. I've just updated the file and it is now the version I'm using.

**Comment by DEHewitt** [comment]
That isn't the way the file looked when I made the commit. What can cause this?

**Comment by jaseeverett** [comment]
Those marks are indicating conflicts (differences) between GitHub and your local computer when you pushed a change.  Maybe edited the file on multiple computers and forgot to pull changes before editing the old version. Normally you would have to resolve them before it allows you to commit a change. Not sure what happened in this instance.

**Comment by HaydenSchilling** [comment]
I see the same issue in the bran2015_download.pbs file

```
#!/bin/bash
 
<<<<<<< HEAD:Simulations/gmc_forward_bran2015.pbs
#PBS -l select=1:ncpus=2:mem=6gb:mpiprocs=2
#PBS -l walltime=48:00:00
#PBS -j oe
#PBS -J 0-419
#PBS -M daniel.hewitt@unsw.edu.au
#PBS -m ae

=======
#PBS -l select=1:ncpus=1:mem=20gb
#PBS -l walltime=12:00:00
#PBS -j oe
#PBS -M daniel.hewitt@unsw.edu.au
#PBS -m ae

 
>>>>>>> a1f91131a86562b0771bee237095240e24f5b8df:BRAN/bran2015_download.pbs
cd $HOME

module purge

<<<<<<< HEAD:Simulations/gmc_forward_bran2015.pbs
module load openmpi/4.0.3
module load python/3.6.5

source mypython3env/bin/activate

mpirun -n 2 python3 gmc_forward_bran2015.py
=======
module load openmpi/3.1.2
module load python/3.6.5


python3 bran2015_download.py
>>>>>>> a1f91131a86562b0771bee237095240e24f5b8df:BRAN/bran2015_download.pbs
```

**Comment by DEHewitt** [comment]
See most recent push for both files.
